# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6caafd27bf367bf32799e6bc79fd579b4641d6dd93daa19164c0ee43c2f658e6f6842559e27eeead84a854d77ef9193d0b274585e58afb61d35e9daec2f97d41

test:
  secret_key_base: afe3c710ab8d353e28e530f624247a75d48101cbb51994b8d88bc6420298c597405e5761fe0bbbf1ad0b1fd0bbac18bb6ffa020cc469b381b5bf4e6a5abfc302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
